In [2]:
#Forward Kinematic
import numpy as np

def DH(theta_n ,a_n, d_n, alpha_n):
  H=np.array([[np.cos(theta_n), -np.sin(theta_n)*np.cos(alpha_n), np.sin(theta_n)*np.sin(alpha_n), a_n*np.cos(theta_n)],
              [np.sin(theta_n), np.cos(theta_n)*np.cos(alpha_n), -np.cos(theta_n)*np.sin(alpha_n), a_n*np.sin(theta_n)],
              [0, np.sin(alpha_n), np.cos(alpha_n), d_n],
              [0, 0, 0, 1]])
  return H

In [4]:
H1 = DH(np.pi/3,0.08920,0,np.pi/2)

H2 = DH(np.pi/3,0,0.425,0)

H3 = DH(np.pi/4,0,0.392,0)

H4 = DH(np.pi/4,0.10930,0,-np.pi/2)

H5 = DH(np.pi/3,0.09475,0,np.pi/2)

H6 = DH(np.pi/3,0.08250,0,0)

H = np.dot(np.dot(np.dot(np.dot(np.dot(H1,H2),H3),H4),H5),H6)

H

array([[ 0.8652594 ,  0.48845783, -0.11284996, -0.67445741],
       [-0.49366345,  0.86937185, -0.02211302,  0.61654639],
       [ 0.0873073 ,  0.0748434 ,  0.99336595,  1.64119673],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [1]:
#Inverse Kinematic
import numpy as np 
x = 4
y = 2
# Calculate the angle of the second joint
theta_2 = np.arctan2(y,x)
print(theta_2)
# The 3x3 rotation matrix of frame 6 relative to frame 0
rot_mat_0_6 = np.array([[-1, 0, 0],
                        [0, -1, 0],
                        [0, 0, 1]])
# The 3x3 rotation matrix of frame 3 relative to frame 0
rot_mat_0_3 = np.array([[-np.sin(theta_2), 0, np.cos(theta_2)],
                        [np.cos(theta_2), 0, np.sin(theta_2)],
                        [0, 1, 0]])
# Calculate the inverse rotation matrix
inv_rot_mat_0_3 = np.linalg.inv(rot_mat_0_3)
 
# Calculate the 3x3 rotation matrix of frame 6 relative to frame 3
rot_mat_3_6 = (inv_rot_mat_0_3).dot(rot_mat_0_6)
print(rot_mat_3_6)
# Calculate the value for theta_5
theta_5 = np.arccos(rot_mat_3_6[2, 2])
print(theta_5)
 
# Calculate the value for theta_6
# -sin(theta_5)cos(theta_6) = rot_mat_3_6[2,0]
# Solving for theta_6...
# rot_mat_3_6[2,0]/-sin(theta_5) = cos(theta_6)
# arccosine(rot_mat_3_6[2,0]/-sin(theta_5)) = theta_6
theta_6 = np.arccos(rot_mat_3_6[2, 0] / -np.sin(theta_5))
print(theta_6)

# Calculate the value for theta_4 using one of the other
# cells in rot_mat_3_6. We'll use the second row, third column.
# cos(theta_4)sin(theta_5) = rot_mat_3_6[1,2]
# cos(theta_4) = rot_mat_3_6[1,2] / sin(theta_5)
# theta_4 = arccosine(rot_mat_3_6[1,2] / sin(theta_5))
theta_4 = np.arccos(rot_mat_3_6[1,2] / np.sin(theta_5))
print(theta_4)


r11 = -np.sin(theta_4) * np.cos(theta_5) * np.cos(theta_6) - np.cos(theta_4) * np.sin(theta_6)
r12 = np.sin(theta_4) * np.cos(theta_5) * np.sin(theta_6) - np.cos(theta_4) * np.cos(theta_6)
r13 = -np.sin(theta_4) * np.sin(theta_5)
r21 = np.cos(theta_4) * np.cos(theta_5) * np.cos(theta_6) - np.sin(theta_4) * np.sin(theta_6)
r22 = -np.cos(theta_4) * np.cos(theta_5) * np.sin(theta_6) - np.sin(theta_4) * np.cos(theta_6)
r23 = np.cos(theta_4) * np.sin(theta_5)
r31 = -np.sin(theta_5) * np.cos(theta_6)
r32 = np.sin(theta_5) * np.sin(theta_6)
r33 = np.cos(theta_5)
 
rot_mat_3_6 = np.array([[r11, r12, r13],
                        [r21, r22, r23],
                        [r31, r32, r33]])

print(rot_mat_3_6)

0.4636476090008061
[[ 0.4472136  -0.89442719  0.        ]
 [ 0.          0.          1.        ]
 [-0.89442719 -0.4472136   0.        ]]
1.5707963267948966
0.46364760900080615
0.0
[[-4.47213595e-01 -8.94427191e-01 -0.00000000e+00]
 [ 5.47678698e-17 -2.73839349e-17  1.00000000e+00]
 [-8.94427191e-01  4.47213595e-01  6.12323400e-17]]
